### ISSUE TITLE
Test existing experiment data files containing CRT data products with the refactored code

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbncode#13]
Some CRT data products are being moved from experiment code to `sbncode`, with change in namespace.
"Legacy` versions are available as well.
We need to verify that this is sufficient to be able to correctly read the old data files.

**Comment by PetrilloAtWork** [comment]
I think we will need to also define what exactly the target is. Two distinct examples come into my mind right now:
1. older data files with `icarus::crt::CRTHit` data products can be read by specifically crafted "legacy" code
2. older data files with `icarus::crt::CRTHit` data products can be read by new software that explicitly refers to the _new_ data product name (for example with calls like `event.getByLabel<std::vector<sbn::crt::CRTHit>>(inputTag)`: note the different namespace)

(in my example, `icarus::crt::CRTHit` is a data product that has been obsoleted and replaced by `sbn::crt::CRTHit` in the current code, but it is still known to the code in a "legacy" form)
Some of the options may require some support by _art_ or ROOT experts.

**Comment by cjbackhouse** [comment]
I found an analysis module in `icaruscode`

 `lar -c CRTSimAnalysis.fcl /pnfs/icarus/persistent/stash/ContinuousIntegration/reference/standard/reco/single_reco_test_icaruscode_Reference.root` doesn't crash, but it also doesn't find any CRT info:

`found 0 CRTData` and `CRTHit products not found! (expected if gen/G4/detsim step)`

seems like the CI file doesn't actually have much CRT stuff in it?

`$ lar -c eventdump.fcl /pnfs/icarus/persistent/stash/ContinuousIntegration/reference/standard/reco/single_reco_test_icaruscode_Reference.root | grep CRT`

tells me there are `icarus::crt::CRTData` vectors, but they are empty in every event.

**Comment by cjbackhouse** [comment]
Gianlucca generated some Corsika events with v08_57_00 with digits but not reconstruction.
They are at `/icarus/data/users/petrillo/LArSoft/production/v08_57_00/e19_prof/logs/standard_detsim_icarus/20200911-00/prodcorsika_standard_icarus_20200911T150809-GenCorsika_20200911T153941-G4_20200911T154640-DetSim.root`.
Or at `/pnfs/icarus/scratch/users/petrillo/for/bckhouse/` for the next few weeks.

The `CRTSimAnalysis` job finds the CRTData (`icarus::crt::CRTData`) objects in that file.

I believe that means that existing code can read existing files (because we retained an `icarus::` copy of the products for now?), without being confused by the new sbnobj objects.

Of course, if one generated new files with sbnobj objects, one would also have to update the analyser code. Maybe this will be fine? Analysers stick with old code until new files are ready, then update code to new object types, or stick with an old tag.

**Comment by wesketchum** [comment]
Believe this is done. Closing.
