### ISSUE TITLE
Document list of "standard" fcl files for SBN jobs

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbncode#28]
Make a nicely documented site for listing standard fcl files. Needs to have an avenue for being updated as needed, with as little maintenance that we can image.

Could also include "common configuration" set.

**Comment by wesketchum** [comment]
Including a list of standard products/labels would also be useful.

**Comment by jzennamo** [comment]
Here is what I understand as the "standard" fcls:

*SBND, w/ cosmics*
- G4: g4_3drift_windows_sce.fcl
- DetSim: detsim_3drift_windows_sce.fcl
- Reco1: reco1_3drift_windows_sce.fcl
- Reco2: reco2_3drift_windows_sce.fcl

*SBND, w/o cosmics*
- G4: g4_enable_spacecharge.fcl
- DetSim: standard_detsim_sbnd.fcl
- Reco1: standard_reco1_sbnd.fcl
- Reco2: reco2_sce.fcl

*ICARUS*
- G4: g4_enable_spacecharge.fcl
- DetSim: multitpc_detsim_icarus.fcl
- (gaus)Reco1+2: reco_icarus_driver_reco_multitpc_gauss_sce.fcl
- (raw) Reco1+2: reco_icarus_driver_reco_multitpc_raw.fcl

Looking forward we should try:
1. Condense the SBND fcls into a single readout duration, if possible 
2. Create a separate "reco1" and "reco2" for ICARUS to enable production more flexibility

**Comment by absolution1** [comment]
Hi @jzennamo 
Some of those are not the standard SBND FCLs.
All of the standard FCLs have standard in the name, so you'd also need
 - standard_g4_sbnd.fcl
 - standard_reco2_sbnd.fcl

If SCE is supposed to be a standard part of the simulation chain then it should be enabled in the appropriate configuration fcl (so that standard_g4_sbnd.fcl picks it up) and we'd need to make override FCLs to disable g4 for those who need it.

I don't think it's really possible to choose a single readout duration as I don't believe its been decided what the standard readout duration is yet.  A DAQ person would know more than me.

----

I used to maintain a list of the standard FCLs on redmine as part of the production documentation: 

https://cdcvs.fnal.gov/redmine/projects/sbndcode/wiki/How_it_works

It's now out of date due to updating the reco pathway.  The page would need updating or deleting depending on where you want to document stuff.

**Comment by jzennamo** [comment]
Hi @absolution1 

What I listed here as "standard" were listed as such because they are the ones being run by production. In some sense they are the "standard production fcls" by force ;) 

I am listing them here so we are aware what is being run by production, can make sure our "standard fcls" match them, and to become aware if there is a large variance in our understanding in the term "standard".

Per the readout duration, I meant that as an aspirational comment since it adds complexity.

**Comment by wesketchum** [comment]
@absolution1 , if Joseph's list and the named "standard" files in SBND don't match, then I think the latter need to be updated as that was the agreed on fcl file list for the latest production, which to my understanding is the desired standard for physics selection work.

**Comment by absolution1** [comment]
Yep, we're saying the same thing @wesketchum 
My understanding is that the only 'things' different between the standard FCLs and what production ran are
 - The space charge service needs enabling in its configuration fcl
 - The standard reco file needs to include the SCE-corrected reconstruction in its pathway

Sim/calib would need prodding to bring the simulation into whatever config they consider standard (enabling space charge I guess). Reco could then update the standard reco2 fcl once the simulation has been brought up to speed.

I dunno how you want to coordinate this I am happy to update the reconstruction fcl when the sim is ready.  If you wanted to collect all of this on a feature branch then plz point me towards it and I'll put the reco update there.

**Comment by wesketchum** [comment]
Claiming done: https://sbnsoftware.github.io/AnalysisInfrastructure/WorkflowManagement/workflow.html

Though of course we need to stay on top of it.
