### ISSUE TITLE
Wildcards in CMake causing ninja problems?

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbncode#35]
CI builds using ninja were failing, and could be fixed by removing wildcards from the cmake files (see branch feature/wketchum_NoWildcard). For now we'll have CI not use ninja, but in the future would be good to arrange things such that ninja can work (while also including everything properly).

Thanks to @vitodb and @cjbackhouse for talking through this.

**Comment by cjbackhouse** [comment]
googling cmake syntax it looks like this should have been done with a line like
`FILE(GLOB SR_DEPENDENCIES $ENV{SBNCODE_DIR}/sbncode/StandardRecord/*.h)`
and then `${SR_DEPENDENCIES}` where I currently have the wildcard directly.

CAFAna/StandardRecord/Proxy/CMakeLists.txt should actually have the same logic too, rather than just the StandardRecord.h it currently depends on.

**Comment by wesketchum** [comment]
Sorry, didn't mention this yesterday, but this has now been fixed with v09_09_00. Closing.
